remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Commander X16 Community
description: Information and discussion about the Commander X16 Microcomputer.
